on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v4
      - name: Check formatting
        run: nix build .#git-hooks
      - name: Build config
        run: |
          mkdir -p ~/.local/state/nix/profiles
          nix run nixpkgs#home-manager -- build --flake .#dlutgehet
