on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v6
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Check formatting
        run: nix build .#git-hooks
      - name: Build config
        run: |
          mkdir -p ~/.local/state/nix/profiles
          nix run nixpkgs#home-manager -- build --flake .#dlutgehet
